### PR TITLE
Add menu_addlink_label to menu API

### PR DESCRIPTION
**Pull request by PrOF-kk**

### CODE REVIEW

**Comment by Medo42** [comment]
I don't quite get what this does... some kind of menu item that runs a script and also displays a value, but it's not clear to me how the script might update the value. Also you seem to call the value "label" which I find confusing, because to me "label" is something you use to describe a field, and not the value of that field.
So, please add an example of how one would use this, and tell me what it's needed for.

**Comment by PrOF-kk** [comment]
This is used when the developer needs to change the value shown only *after* the script is executed. Here's an example of when this is be used: https://github.com/Gang-Garrison-2/Gang-Garrison-2/pull/232
And here's where I got the idea: https://www.ganggarrison.com/forums/index.php?topic=37597.msg1294597#msg1294597 none of the suggestions worked correctly

**Comment by Medo42** [comment]
Use this instead please: https://github.com/Gang-Garrison-2/Gang-Garrison-2/commit/30b584bcbba31238da5361e41891ead8bd43bf34

**Comment by Medo42** [comment]
The main other difference is that it uses menu_value instead of menu_var for the display value, which is more consistent with other menu items where menu_value is what is shown, and menu_var is a reference to the actual value. I looked at your map rotation picker code and noticed that you are using a "local" (instance-scoped) variable for menu_var, which is unusual in the menu system (all other uses of this use global variables) and which feels dirty (since the menu code doesn't really say which instance scope it will use). So I catered to this use of the script instead by letting it return the new display value, meaning you don't need any variable to reference.

**Comment by Medo42** [comment]
You can use it just like your own implementation, just pass the initial display value as the second parameter instead of the variable name, and use return in your third-parameter script instead of setting the variable.

**Pull request closed without merging**
